apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cluster-service-account
roleRef:
  kind: Role
  name: myrole
  apiGroup: rbac.authorization.k8s.io