apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: mongo-sa
roleRef:
- kind: Role
  name: role
  apiGroup: rbac.authorization.k8s.io