apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-config
data:
  mongo-init.js: |
    rs.initiate(
       {
          _id: "rs0",
          members: [
             { _id: 0, host: "mongo-0.mongo.default.svc.cluster.local:27017" },
             { _id: 1, host: "mongo-1.mongo.default.svc.cluster.local:27017" },
             { _id: 2, host: "mongo-2.mongo.default.svc.cluster.local:27017", priority: 0 }
          ]
       }
    )
    use admin
    db.createUser({
      user: "mostafa",
      pwd: 'MTIzNDU2',
      roles: [ { role: "root", db: "admin"} ]
    })
    db.auth("mostafa", "MTIzNDU2")