apiVersion: apps/v1    #------- StatefulSet configuration
kind: StatefulSet
metadata:
  name: mongo
spec:
  serviceName: "mongo-service"
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        environment: dev
    spec:
      serviceAccountName: mongo-sa
      terminationGracePeriodSeconds: 10
      containers:
        - name: mongo
          image: us-central1-docker.pkg.dev/swift-radar-399606/my-repo/mongodb
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db 
            - name: config-volume
              mountPath: /etc/mongo
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
          args:
            - "--replSet"
            - rs0
            - "--auth"   # Enable authentication
            - "--keyFile"
            - "/keys/mongodb-keyfile.txt"

        - name: mongo-sidecar
          image: us-central1-docker.pkg.dev/swift-radar-399606/my-repo/cvallance/mongo-k8s-sidecar
          env:
            - name: MONGO_SIDECAR_POD_LABELS
              value: "app=mongo,environment=dev"
            - name: KUBERNETES_MONGO_SERVICE_NAME
              value: "mongo-service"
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-credentials
                  key: password
            - name: MONGODB_DATABASE
              value: "admin"
      volumes:
        - name: config-volume
          configMap:
            name: mongo-config

  volumeClaimTemplates:
  - metadata:
      name: mongo-persistent-storage
      annotations:
        volume.beta.kubernetes.io/storage-class: "fast-ssd"
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
