apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-sa
secrets:
  - name: mongo-credentials
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: myrole
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myrole-binding
subjects:
- kind: ServiceAccount
  name: mongo-sa
roleRef:
  kind: Role
  name: myrole
  apiGroup: rbac.authorization.k8s.io